In [44]:
import torch
import torch.nn.functional as F
import pandas as pd

from torch.utils.data import DataLoader, Dataset, TensorDataset, Sampler
from keras.preprocessing.sequence import pad_sequences
from pytorch_pretrained_bert import BertAdam
from pytorch_pretrained_bert import BertForSequenceClassification

In [2]:
data = pd.read_csv('./data/bert_data.csv')

In [3]:
data

review sentiment  \
0      One of the other reviewers has mentioned that ...  positive   
1      A wonderful little production. <br /><br />The...  positive   
2      I thought this was a wonderful way to spend ti...  positive   
3      Basically there's a family where a little boy ...  negative   
4      Petter Mattei's "Love in the Time of Money" is...  positive   
5      Probably my all-time favorite movie, a story o...  positive   
6      I sure would like to see a resurrection of a u...  positive   
7      This show was an amazing, fresh & innovative i...  negative   
8      Encouraged by the positive comments about this...  negative   
9      If you like original gut wrenching laughter yo...  positive   
10     Phil the Alien is one of those quirky films wh...  negative   
11     I saw this movie when I was about 12 when it c...  negative   
12     So im not a big fan of Boll's work but then ag...  negative   
13     The cast played Shakespeare.<br /><br />Shakes...  negative   
14     This a fantastic movie of three prisoners who ...  positive   
15     Kind of drawn in by the erotic scenes, only to...  negative   
16     Some films just simply should not be remade. T...  positive   
17     This movie made it into one of my top 10 most ...  negative   
18     I remember this film,it was the first film i h...  positive   
19     An awful film! It must have been up against so...  negative   
20     After the success of Die Hard and it's sequels...  positive   
21     I had the terrible misfortune of having to vie...  negative   
22     What an absolutely stunning movie, if you have...  positive   
23     First of all, let's get a few things straight ...  negative   
24     This was the worst movie I saw at WorldFest an...  negative   
25     The Karen Carpenter Story shows a little more ...  positive   
26     "The Cell" is an exotic masterpiece, a dizzyin...  positive   
27     This film tried to be too many things all at o...  negative   
28     This movie was so frustrating. Everything seem...  negative   
29     'War movie' is a Hollywood genre that has been...  positive   
...                                                  ...       ...   
49970  This movie is a total dog. I found myself stra...  negative   
49971  With several name actors (Lance Henrikson, Dav...  negative   
49972  The future of fantasy never looked so dark! Ch...  negative   
49973  The title leads viewers to believe that this i...  negative   
49974  For the most part, "Michael" is a disaster – t...  negative   
49975  90 minutes of Mindy...Mindy is a tease to boyf...  negative   
49976  I saw the movie in the theater at its release,...  positive   
49977  Dog Bite Dog isn't going to be for everyone, b...  positive   
49978  Halloween is one of those movies that gets you...  positive   
49979  I saw this with high expectations. Come on, it...  negative   
49980  A stunning film of high quality.<br /><br />Ap...  positive   
49981  And I repeat, please do not see this movie! Th...  negative   
49982  To be hones, I used to like this show and watc...  negative   
49983  I loved it, having been a fan of the original ...  positive   
49984  Hello it is I Derrick Cannon and I welcome you...  negative   
49985  Imaginary Heroes is clearly the best film of t...  positive   
49986  This movie is a disgrace to the Major League F...  negative   
49987  A remake of Alejandro Amenabar's Abre los Ojos...  negative   
49988  When I first tuned in on this morning news, I ...  negative   
49989  I got this one a few weeks ago and love it! It...  positive   
49990  Lame, lame, lame!!! A 90-minute cringe-fest th...  negative   
49991  Les Visiteurs, the first movie about the medie...  negative   
49992  John Garfield plays a Marine who is blinded by...  positive   
49993  Robert Colomb has two full-time jobs. He's kno...  negative   
49994  This is your typical junk comedy.<br /><br />T...  negative   
49995  I thought this movie did a down right good job...  po

In [53]:
def convert_ids_to_tensor(lst):
    org_id_lst = [eval(i)[:512] for i in lst]
    org_ids = pad_sequences(org_id_lst,maxlen=512,padding='post')
    org_tensor = torch.from_numpy(org_ids)
    return org_tensor

In [152]:
y = torch.tensor(data.sentiment.replace({'negative':0,'positive':1}).values).type(torch.float32).view(-1,1)

In [110]:
org_tensor = convert_ids_to_tensor(data.org_ids.values)
trans_tensor = convert_ids_to_tensor(data.ko_ids.values)

In [163]:
training_td = TensorDataset(org_tensor[:20].type(torch.int64),y[:20])
aux_td = TensorDataset(org_tensor.type(torch.int64),trans_tensor.type(torch.int64),y)

In [280]:
test_td = TensorDataset(org_tensor[-10000:].type(torch.int64),y[-10000:])

In [283]:
len(test_td)

10000

In [47]:
class FixlengthSampler(Sampler):
    def __init__(self, data_source, length=None):
        self.data_source = data_source
        self.length = length if length is not None else len(self.data_source)
    def __iter__(self,):
        return iter(torch.randint(low=0,high=len(self.data_source),size=(self.length,)))
    def __len__(self): 
        return self.length

In [304]:
training_steps = 10
aux_batch_size = 8
training_batch_size = 16
test_batch_size = 16

training_sampler = FixlengthSampler(training_td,length=training_steps*training_batch_size)
training_dl = DataLoader(training_td,batch_size=training_batch_size,sampler=training_sampler)

aux_sampler = FixlengthSampler(aux_td,length=training_steps*aux_batch_size)
aux_dl = DataLoader(aux_td,batch_size=aux_batch_size,sampler=aux_sampler)

test_dl = DataLoader(test_td,batch_size=16)

In [305]:
### quick test
aux_iter = iter(aux_dl)
bax1,bax2,bay = next(aux_iter)

In [172]:
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=1)
model = model.to(device)

In [300]:
def kl_div(bl1,bl2):
    bl1_prob,bl2_prob = torch.sigmoid(bl1), torch.sigmoid(bl2)
    return (bl1_prob*(bl1_prob/bl2_prob).log()).mean()

In [314]:
# this is the same example in wiki
P = torch.Tensor([0.36, 0.48, 0.16])
Q = torch.Tensor([0.333, 0.333, 0.333])
(P * (P / Q).log()).mean()
# tensor(0.0863), 10.2 µs ± 508
F.kl_div(Q.log(), P, None, None, 'batchmean')
# tensor(0.0863), 14.1 µs ± 408 ns

tensor(0.0288)

In [320]:
def inverse_sig(x):
    return torch.log(x/(1-x))

In [321]:
kl_div(inverse_sig(P),inverse_sig(Q))

tensor(0.0288)

In [322]:
kl_div(torch.tensor(1.9),torch.tensor(5.8))

tensor(-0.1186)

In [323]:
F.kl_div(torch.tensor(5.8).sigmoid().log(), torch.tensor(1.9).sigmoid(), reduction='batchmean')

tensor(-0.1186)

In [276]:
opt = BertAdam(model.parameters(),
               lr=2e-5,
               warmup=0.02, 
               t_total=training_steps,
              )

In [ ]:
def eval_model(model):
    acc = 0.0
    for bx,by in test_dl:
        attention_mask = bx > 0 
        bx,by = bx.to(device),by.to(device)
        bl = model(bx,attention_mask=attention_mask)
        bacc = ((bl >= 0).astype(torch.float32) == by).sum()
        acc += bacc
    acc = acc/len(text_dl)
    return acc

In [294]:
uda = True
lamda = 0.2
training_iter = iter(training_dl)
aux_iter = iter(aux_dl)
# eval_per_steps = int(training_steps/10)
eval_per_steps = 100

model = model.train()
for i in range(training_steps):
    bx,by = next(training_iter)
    bx,by = bx.to(device),by.to(device)
    
    if uda: 
        bax1,bax2,bay = next(aux_iter)
        bax1,bax2,bay = bax1.to(device),bax2.to(device),bay.to(device)
        
    progress = torch.tensor(i/training_steps)
    ita = cal_ita(progress)
    
    attention_mask = bx > 0
    bl = model(bx,attention_mask=attention_mask)
    if uda:
        bal1,bal2 = model(bax1),model(bax2)
        
        loss = tsa_loss(bl,by,ita)
        aux_loss = kl_div(bal1,bal2)
        loss = loss + lamda * aux_loss
    else:
#         loss = tsa_loss(bl,by)
        loss = torch.binary_cross_entropy_with_logits(bl,by)
    
    opt.zero_grad()
    loss.backward()
    opt.step()
    
#     loss =  
    if i % eval_per_steps == 0:
        model = model.eval()
        acc = eval_model(model)
        model = model.train()
        
    break
    
    print(ita)

TypeError: tsa_loss() missing 1 required positional argument: 'ita'

In [298]:
loss = tsa_loss(bl,by,ita)
loss

tensor(0.7853, grad_fn=<MulBackward0>)

In [301]:
aux_loss = kl_div(bl,)
aux_loss

tensor(-0.0634, grad_fn=<MeanBackward1>)

In [ ]:
torch.kl_div(by)

In [302]:
bl

tensor([[0.0854],
        [0.2212],
        [0.2692],
        [0.2029],
        [0.1858],
        [0.2984],
        [0.1517],
        [0.2177],
        [0.1325],
        [0.1521],
        [0.2172],
        [0.3126],
        [0.3012],
        [0.0492],
        [0.3645],
        [0.2692]], grad_fn=<AddmmBackward>)

In [303]:
by

tensor([[1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.]])

In [269]:
tsa_loss

<function __main__.tsa_loss(logits, labels, ita)>

In [202]:
(P * (P / Q).log()).sum()

tensor(0.0863)

In [97]:
logits = torch.tensor([[10.,-3.]])
logits

tensor([[10., -3.]])

In [148]:
labels = torch.tensor([[1,0]])
labels

tensor([[1, 0]])

In [149]:
labels.dtype

torch.int64

In [103]:
tsa_loss(logits,labels,ita)

tensor(0.)

In [104]:
probs = torch.sigmoid(logits)
probs 

tensor([[1.0000, 0.0474]])

In [105]:
confi_probs = 1 - torch.abs(probs - labels)
confi_probs

tensor([[1.0000, 0.9526]])

In [106]:
confi_probs

tensor([[1.0000, 0.9526]])

In [107]:
masks = (confi_probs <= ita).type(torch.float32)
masks

tensor([[0., 0.]])

In [108]:
F.binary_cross_entropy(probs,labels,reduction='none') * masks

tensor([[0., 0.]])

In [109]:
F.binary_cross_entropy_with_logits(logits,labels,reduction='none')

tensor([[4.5418e-05, 4.8587e-02]])

In [296]:
def tsa_loss(logits,labels,ita):
    probs = torch.sigmoid(logits)
    confi_probs = 1 - torch.abs(probs - labels)
    masks = (confi_probs <= ita).type(torch.float32)
#     print(masks)
    loss = torch.mean(F.binary_cross_entropy(probs,labels,reduction='none') * masks)
    loss = 1/masks.mean()*loss
    return loss
def cal_ita(progress):
    return torch.exp((progress-1)*5)*(1-1/2)+1/2

In [265]:
tsa_loss(logits,labels.type(torch.float32),ita)

tensor([[0., 1.]])


tensor(3.0486)

In [266]:
labels

tensor([[1, 0]])

In [267]:
logits

tensor([[10.,  3.]])

In [ ]:
F.